baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Curia Damiano'
theme = 'stack'

[params]
	mainSections = ['posts']

	[params.sidebar]
		subtitle = 'Insert your blog description here...'

		[params.sidebar.avatar]
			enabled = true
			local = false
			src = '/img/avatar.jpeg'

	[params.widgets]

		[[params.widgets.homepage]]
			type = 'search'

		[[params.widgets.homepage]]
			type = 'archives'

			[params.widgets.homepage.params]
				limit = 5

		[[params.widgets.homepage]]
			type = 'categories'

			[params.widgets.homepage.params]
				limit = 10

		[[params.widgets.homepage]]
			type = 'tag-cloud'

			[params.widgets.homepage.params]
				limit = 10

[menu]

	[[menu.main]]
		identifier = 'home'
		name = 'Home'
		url = '/'
		weight = 1
		[menu.main.params]
			icon = 'home'

	[[menu.main]]
		identifier = 'archives'
		name = 'Archives'
		url = '/archives/'
		weight = 2
		[menu.main.params]
			icon = 'archives'

	[[menu.main]]
		identifier = 'search'
		name = 'Search'
		url = '/search/'
		weight = 3
		[menu.main.params]
			icon = 'search'

	[[menu.main]]
		identifier = 'about'
		name = 'About Me'
		url = '/about/'
		weight = 4
		[menu.main.params]
			icon = 'user'

	[[menu.social]]
		identifier = 'email'
		name = 'Email'
		url = 'mailto:damiano.curia@gmail.com'
		weight = 1
		[menu.social.params]
			icon = 'mail'
			newTab = true

	[[menu.social]]
		identifier = 'github'
		name = 'GitHub'
		url = 'https://github.com/curia-damiano'
		weight = 2
		[menu.social.params]
			icon = 'brand-github'
			newTab = true

	[[menu.social]]
		identifier = 'linkedin'
		name = 'LinkedIn'
		url = 'https://www.linkedin.com/in/damianocuria/'
		weight = 3
		[menu.social.params]
			icon = 'brand-linkedin'
			newTab = true

	[[menu.social]]
		identifier = 'rss'
		name = 'RSS'
		url = '/index.xml'
		weight = 4
		[menu.social.params]
			icon = 'rss'
			newTab = true

	[[menu.social]]
		identifier = 'threads'
		name = 'Threads'
		url = 'https://www.threads.net/@damiano.curia'
		weight = 5
		[menu.social.params]
			icon = 'brand-threads'
			newTab = true

	[[menu.social]]
		identifier = 'x'
		name = 'X'
		url = 'https://x.com/CuriaDamiano'
		weight = 6
		[menu.social.params]
			icon = 'brand-x'
			newTab = true
